language: java
jdk:
  - openjdk-11

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: pjt-webservice-deploy # 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: pjt-tech/freelec-springboot2-webservice #Github 주소
      branch: main

before_install:
  - chmod +x gradlew

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      -pjint704@gmail.com

before_deploy:
      - zip -r spring_deploy_test *
      - mkdir -p deploy
      - mv spring_deploy_test.zip deploy/spring_deploy_test.zip

  deploy:
  # S3로 파일업로드
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repos settings에 설정된 값
    bucket: spring-deploy-test-build # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      all_branches: true # master말고 다른 모든 브런치 허용